on:
  push:
    branches:
    - master
    tags:
    - '**'

name: push image
jobs:
  dockerpush:
    name: docker build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.0.0
    - name: extract tag
      id: vars
      run: echo ::set-output name=alpine_version::$(grep '^FROM alpine' Dockerfile  | cut -d ' ' -f 2 | cut -d ':' -f 2)
    - run: echo "Pushing version ${{ steps.vars.outputs.alpine_version }}"
    - name: Docker Login
      uses: azure/docker-login@v1
      with:
        login-server: docker.pkg.github.com
        username: hazcod
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build & Push image
      run: |
        export IMAGENAME="docker.pkg.github.com/ironpeakservices/iron-alpine/iron-alpine:${{ steps.vars.outputs.alpine_version }}"
        docker build --tag "$IMAGENAME" .
        docker create --name image "$IMAGENAME"
        docker export image | docker import - "$IMAGENAME"
        docker push "$IMAGENAME"
    - name: Create GitHub release
      uses: sondreb/action-release@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        draft: false
        prerelease: false
        tag: ${{ steps.vars.outputs.alpine_version }}
