
on:
  push:
    branches:
    - master

name: Publish Image
jobs:
  dockerpush:
    name: docker build
    runs-on: ubuntu-latest
    steps:
    - 
      uses: actions/checkout@v2.3.4
    - 
      id: vars
      run: |
        echo ::set-output name=alpine_version::$(grep '^FROM alpine' Dockerfile | cut -d ' ' -f 2 | cut -d ':' -f 2)
        echo "Using alpine version ${{ steps.vars.outputs.alpine_version }}"
    - 
      name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@3.01
      with:
        registry: ghcr.io
        name: "ghcr.io/ironpeakservices/iron-alpine:${{ steps.vars.outputs.alpine_version }}"
        username: ${{ github.actor }}
        password: ${{ secrets.PACKAGE_TOKEN }}
    - 
      name: Create GitHub release
      uses: actions/create-release@v1.1.4
      with:
          tag_name: ${{ steps.vars.outputs.alpine_version }}
          release_name: iron-alpine
          draft: false
          prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.PACKAGE_TOKEN }}
